<?php

    require('../data/src/php.php');
    // Check if the user is logged in, otherwise redirect to login page
    if(!isset($_SESSION["loggedin"]) || $_SESSION["loggedin"] !== true){
        header("location: ./login");
        exit;
    } else
        echo '<script nonce="inline" type="text/JavaScript"> javascript:history.back(); </script>';
        header("location: /index?=redirected");

?>